const CONFIG = {
    particles: {
        get count() {
            const isMobile = /Android|webOS|iPhone|iPad|iPod/i.test(navigator.userAgent);
            const isLowEnd = navigator.hardwareConcurrency <= 4;

            if (isMobile || isLowEnd) return 15000;
            if (navigator.hardwareConcurrency >= 8) return 40000;
            return 25000;
        },
        backgroundCount: 450,
        defaultSize: 7.0,
    },
    rendering: {
        pixelRatio: Math.min(window.devicePixelRatio, 2),
        antialias: false,
        powerPreference: 'high-performance',
        toneMappingExposure: 1.5,
    },
    bloom: {
        threshold: 0.1,
        strength: 2.0,
        radius: 0.5,
    },
    camera: {
        fov: 60,
        near: 0.1,
        far: 1000,
        positionZ: 40,
    },
    video: {
        width: 320,
        height: 240,
        facingMode: 'user',
    },
    handDetection: {
        fps: 20,
        numHands: 2,
    },
    gestures: {
        swipeThreshold: 0.15,
        swipeCooldown: 1000,
        swipeVelocityMin: 0.15,
        modeThresholds: {
            enter: 0.6,
            exit: 0.35,
            decay: 0.05,
        },
    },
    filters: {
        freq: 60,
        minCutoff: 1.0,
        beta: 0.08,
        dCutoff: 1.0,
    },
    physics: {
        smoothingFactor: 0.1,
        gestureSmoothingFactor: 0.15,
        windSmoothingFactor: 0.1,
        rotationSmoothingFactor: 0.15,
        baseRotationSpeed: 0.05,
        maxGestureRotationSpeed: 3.0,
        fistRotationMultiplier: 1.75,
        minRotationVelocity: 0.15,
        rotationIdleDecay: 0.15,
    },
    controls: {
        glow: {
            sliderMin: 0.0,
            sliderMax: 4.0,
            default: 0.0,
            step: 0.1,
            displayPrecision: 2,
            smoothing: 0.08,
            gamma: 1.35,
            strengthMin: 0.25,
            strengthMax: 3.5,
            radiusMin: 0.2,
            radiusMax: 0.85,
            thresholdMin: 0.2,
            thresholdMax: 0.85,
        },
        size: {
            sliderMin: 1.0,
            sliderMax: 10.0,
            default: 9.9,
            step: 0.1,
            displayPrecision: 2,
            smoothing: 0.1,
            gamma: 1.15,
            baseMin: 2.5,
            baseMax: 9.5,
        },
        density: {
            sliderMin: 0.0,
            sliderMax: 1.0,
            default: 1.0,
            step: 0.01,
            displayPrecision: 2,
            smoothing: 0.12,
            gamma: 0.85,
            minFactor: 0.02,
            maxFactor: 1.0,
        },
        spacing: {
            sliderMin: 0.3,
            sliderMax: 4.0,
            default: 4.0,
            step: 0.1,
            displayPrecision: 2,
            smoothing: 0.12,
            gamma: 0.75,
        },
        dotSize: {
            smoothing: 0.12,
            min: {
                sliderMin: 0.4,
                sliderMax: 2.0,
                default: 0.65,
                step: 0.05,
                displayPrecision: 2,
            },
            max: {
                sliderMin: 1.0,
                sliderMax: 5.0,
                default: 2.95,
                step: 0.05,
                displayPrecision: 2,
            },
        },
        halo: {
            sliderMin: 0.3,
            sliderMax: 2.5,
            default: 0.8,
            step: 0.05,
            displayPrecision: 2,
            smoothing: 0.1,
        },
        bokehColor: {
            default: '#da1010',
        },
        color: {
            default: '#e0392c',
        },
    },
};

const PHYSICS_MODES = {
    NORMAL: {
        name: 'Normal',
        icon: '✨',
        description: 'Default particle behavior',
        gravity: 0,
        friction: 0.98,
        bounce: 0,
        magneticStrength: 0,
        viscosity: 1.0,
        turbulence: 0,
        quantumJump: 0,
    },
    GRAVITY: {
        name: 'Gravity',
        icon: '🌍',
        description: 'Particles fall with realistic physics',
        gravity: 0.25,
        friction: 0.995,
        bounce: 0.8,
        floorY: -25,
        magneticStrength: 0,
        viscosity: 0.999,
        turbulence: 0.03,
        quantumJump: 0,
    },
    MAGNETIC: {
        name: 'Magnetic',
        icon: '🧲',
        description: 'Particles attract or repel from hands',
        gravity: 0.01,
        friction: 0.98,
        bounce: 0,
        magneticStrength: 5.0,
        magneticRange: 50,
        magneticFalloff: 1.5,
        viscosity: 0.96,
        turbulence: 0.02,
        quantumJump: 0,
    },
    FLUID: {
        name: 'Fluid',
        icon: '💧',
        description: 'Liquid-like flowing motion',
        gravity: 0.08,
        friction: 0.95,
        bounce: 0.4,
        floorY: -20,
        viscosity: 0.92,
        surfaceTension: 0.3,
        turbulence: 0.1,
        flowiness: 1.5,
        magneticStrength: 1.2,
        magneticRange: 30,
        magneticFalloff: 2.0,
        quantumJump: 0,
    },
    QUANTUM: {
        name: 'Quantum',
        icon: '⚛️',
        description: 'Particles teleport and phase shift',
        gravity: 0,
        friction: 0.99,
        bounce: 0,
        magneticStrength: 2.0,
        magneticRange: 40,
        magneticFalloff: 2.0,
        viscosity: 0.97,
        turbulence: 0.3,
        quantumJump: 0.002,
        phaseShift: 0.08,
        entanglement: 0.02,
    },
    ANTIGRAVITY: {
        name: 'Anti-Gravity',
        icon: '🎈',
        description: 'Particles float upward',
        gravity: -0.18,
        friction: 0.994,
        bounce: 0.7,
        ceilingY: 25,
        magneticStrength: 0,
        viscosity: 0.98,
        turbulence: 0.05,
        quantumJump: 0,
    },
};

export { PHYSICS_MODES };
export default CONFIG;
